---
title: "Analyses & Projects"
output: html_document
---

```{r setup_analyses, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

Assignment 1

**Title:** Assignment 1: Analyzing Rock Climbing Photo Points in Boulder, CO, Using R Markdown and GitHub  
**File:** `assignment-1.Rmd` → `assignment-1.html`

- **Open the analysis:** [assignment-1.html](assignment-1.html)
- **What it shows:** A map and pie chart of photo points near climbing walls in Boulder, CO. 
- **Skills:** R Markdown, ggplot2, GitHub.

Assignment 2

**Title:** Assignment 2: Using LiDAR to Analyze Slope Steepness in El Portal, CA  
**File:** `assignment-2.Rmd` → `assignment-2.html`

- **Open the analysis:** [assignment-2.html](assignment-2.html)
- **What it shows:** A geovisualization of slope steepness in El Portal, CA. 
- **Skills:** LiDAR, R Markdown.


Assignment 3

**Title:** Assignment 3: Most Common Land Cover Types in Michigan Flickr Photos Across Time
**File:** `assignment-3.Rmd` → `assignment-3.html`

- **Open the analysis:** [assignment-3.html](assignment-3.html)
- **What it shows:** Visualizations of trends in land cover classes in Michigan Flickr photos.  
- **Skills:** Spatiotemporal analysis, animation, R Markdown.

Assignment 4

**Title:** Assignment 4: Sentiment Analysis of Taylor Swift's 'Track Fives'
**File:** `assignment-4.Rmd` → `assignment-4.html`

- **Open the analysis:** [assignment-4.html](assignment-4.html)
- **What it shows:** Charts and tables describing the sentiment of Taylor Swift songs.   
- **Skills:**  Sentiment analysis, R Markdown.

Assignment 5

**Title:** Assignment 5: Generalized Linear Models and Clustering
**File:** `assignment-5.Rmd` → `assignment-5.html`

- **Open the analysis:** [assignment-5.html](assignment-5.html)
- **What it shows:** Interpretation of a generalized linear model that explains urban change in Salt Lake City. A cluster analysis of outdoor recreation amenities across the United States.     
- **Skills:**  Generalized linear models, clustering techniques, R Markdown.
